image: php:7.4

# services:
#   - mysql:latest

before_script:
  - apt-get update -qq
  - apt-get install -y -qq git
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
  - cp .env.testing .env
  - php artisan key:generate
  - touch storage/app/db.sqlite
  - php artisan migrate

test:
  stage: test
  script:
  - php artisan test